name:                api-service-template
version:             0.1.0.0
github:              "learnew2/labforge"
license:             GPL-3.0-or-later
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2025 Ilya Zamaratskikh"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/learnew2/labforge#readme>

dependencies:
- base >= 4.7 && < 5
- persistent == 2.14.6.0
- persistent-postgresql == 2.13.6.1
- monad-logger == 0.3.40
- servant-server == 0.19.2
- warp == 3.3.25
- aeson == 2.1.2.1
- transformers == 0.5.6.2
- mtl == 2.2.2
- wai-logger == 2.4.0
- resource-pool == 0.4.0.0
- text == 2.0.2
- persistent-sqlite == 2.13.2.0
- bytestring == 0.11.5.2
- optparse-applicative == 0.17.1.0
- load-env == 0.2.1.0
- directory == 1.3.7.1
- filepath == 1.4.2.2
- servant-client == 0.19
- http-conduit == 2.3.8.1
- http-types == 0.12.3
- exceptions == 0.10.5
- keycloak-api
- api-common

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  api-service-template:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api-service-template

#tests:
#  api-service-template-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - api-service-template
