name:                rabbitmq-pool-template
version:             0.1.0.0
github:              "learnew2/rabbitmq-pool-template"
license:             GPL-3.0-or-later
author:              "Ilya Zamaratskikh"
maintainer:          "mrtstg@yandex.ru"
copyright:           "2025 Ilya Zamaratskikh"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/learnew2/rabbitmq-pool-template#readme>

dependencies:
- base >= 4.7 && < 5
- monad-logger == 0.3.40
- aeson == 2.1.2.1
- transformers == 0.5.6.2
- text == 2.0.2
- bytestring == 0.11.5.2
- load-env == 0.2.1.0
- servant-client == 0.19
- http-conduit == 2.3.8.1
- servant-server == 0.19.2
- http-types == 0.12.3
- exceptions == 0.10.5
- optparse-applicative == 0.17.1.0
- directory == 1.3.7.1
- async == 2.2.4
- amqp == 0.22.1
- mtl == 2.2.2
- stm == 2.5.1.0
- keycloak-api
- api-common

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rabbitmq-pool-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rabbitmq-pool-template

#tests:
#  rabbitmq-pool-template-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - rabbitmq-pool-template
